health:
  config:
    enabled: false
info:
  app:
    name: Recipe Book
logging:
  file:
    name: logs/recipe.log
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
recipeBook:
  seedDbIfEmpty: false
  recipeFile: 'src/main/resources/recipes.json'
server:
  compression:
    enabled: true
  forward-headers-strategy: NATIVE
  servlet:
    session:
      persistent: true
      timeout: 240m
      cookie:
        secure: false
        http-only: false
spring:
  application:
    name: RecipeBook
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          lob:
            non_contextual_creation: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 50
  resources:
    cache:
      period: 1D
  servlet:
    multipart:
      location: ${java.io.tmpdir}
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
